main: com.kookykraftmc.kits.CatKits
name: CatKits
version: 0.1
description: Make kits ez pz.
author: TimeTheCat
commands:
  createkit:
    usage: /createkit <name>
    description: Create a kit.
    default: op
  kit:
    usage: /kit <name>
    description: Use a kit.
    default: default.
